prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 30
keybindings:
  prs:
    - key: m
      command: >
        cd {{.RepoPath}} &&
        gh pr merge {{.PrNumber}} --auto
    - key: u
      command: >
        cd {{.RepoPath}} &&
        git branch --show-current | read oldBranch &&
        gh co {{.PrNumber}} &&
        git fetch &&
        git rebase origin/master &&
        git push --force-with-lease &&
        git checkout $oldBranch
    - key: f
      command: >
        cd {{.RepoPath}} &&
        git branch --show-current | read oldBranch &&
        cd protected/hyperion &&
        npm run format:prettier &&
        git commit --all --no-edit --amend &&
        git push --force-with-lease &&
        git checkout $oldBranch
repoPaths:
  struqtur/struqtur-legacy: ~/code/struqtur-legacy
  struqtur/infrastructure: ~/code/infrastructure
  struqtur/struqtur-native-android: ~/code/struqtur-native-android
pager:
  diff: "bat --paging always"
